In [83]:
import pandas as pd
marks_data=pd.read_csv("marksdata2.csv")
marks_data

,Gender,TravelMethod,TravelTime,PartTimeJob,Relationship,Father's_education,Mother's_education,StudyHours,AttendenceLecs,Concentrate,Friends,SocialMediaTime,extra curricular,HowYouPrepare,StudyPattern,Rate yourself,Marks
0,Male,By public vehicle,Less than 1 hour,No,No,Holds a degree,Holds a degree,Less than 2 hours,Sometimes,Sometimes,Yes,More than 2 hours,Yes,"Self studying, Group studying along with friends",I study regularly,Topper student (85-100),80 to 89
1,Male,By private vehicle,Less than 1 hour,No,Yes,Holds a degree,Secondary school (grade 6 - 12),Less than 5 hours,Sometimes,Sometimes,Yes,Less than 2 hours,Yes,"Self studying, Group studying along with friends",I study regularly,Topper student (85-100),80 to 89
2,Male,By public vehicle,More than 1 hour,No,No,Primary school (grade 1 - 5),Secondary school (grade 6 - 12),Less than 2 hours,Always,Sometimes,No,More than 2 hours,No,Self studying,Closest date to the exam,Average (40 - 65),60 to 69
3,Male,By private vehicle,Less than 1 hour,No,Yes,Holds a degree,Secondary school (grade 6 - 12),More than 5 hours,Sometimes,Sometimes,Yes,Less than 2 hours,Yes,"Self studying, Group studying along with friends",I study regularly,Topper student (85-100),80 to 89
4,Male,By public vehicle,Less than 30 minutes,No,No,Secondary school (grade 6 - 12),Holds a degree,Less than 2 hours,Always,Sometimes,No,None,No,Self studying,Closest date to the exam,Above average (65 - 85),70 to 79
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
137,Male,By public vehicle,Less than 1 hour,Yes,No,Secondary school (grade 6 - 12),Primary school (grade 1 - 5),Less than 2 hours,Sometimes,Sometimes,Yes,More than 2 hours,Yes,"Self studying, Group studying along with friends",Closest date to the exam,Average (40 - 65),50 to 59
138,Male,By public vehicle,More than 1 hour,Yes,No,Secondary school (grade 6 - 12),Primary school (grade 1 - 5),Less than 2 hours,Sometimes,Sometimes,No,More than 2 hours,No,Self studying,Closest date to the exam,Average (40 - 65),30 to 39
139,Male,By private vehicle,More than 1 hour,No,Yes,Secondary school (grade 6 - 12),Secondary school (grade 6 - 12),Less than 1 hour,Sometimes,Sometimes,No,More than 2 hours,Yes,Self studying,Closest date to the exam,Average (40 - 65),40 to 49
140,Female,By private vehicle,Less than 15 minutes,No,No,Holds a degree,Holds a degree,Less than 1 hour,Sometimes,Sometimes,Yes,More than 2 hours,Yes,Self studying,Closest date to the exam,Below average (less than 40),20 to 29
141,Male,By public vehicle,Less than 1 hour,No,No,Secondary school (grade 6 - 12),Secondary school (grade 6 - 12),Less than 5 hours,Always,Sometimes,Yes,Less than 2 hours,Yes,"Self studying, Group studying along with frien...",I study regularly,Topper student (85-100),90 to 100

In [84]:
dataMapping={
    "By public vehicle":1,
    "By private vehicle":0
}

In [85]:
marks_data["TravelMethod"]=marks_data["TravelMethod"].map(dataMapping)
marks_data

,Gender,TravelMethod,TravelTime,PartTimeJob,Relationship,Father's_education,Mother's_education,StudyHours,AttendenceLecs,Concentrate,Friends,SocialMediaTime,extra curricular,HowYouPrepare,StudyPattern,Rate yourself,Marks
0,Male,1,Less than 1 hour,No,No,Holds a degree,Holds a degree,Less than 2 hours,Sometimes,Sometimes,Yes,More than 2 hours,Yes,"Self studying, Group studying along with friends",I study regularly,Topper student (85-100),80 to 89
1,Male,0,Less than 1 hour,No,Yes,Holds a degree,Secondary school (grade 6 - 12),Less than 5 hours,Sometimes,Sometimes,Yes,Less than 2 hours,Yes,"Self studying, Group studying along with friends",I study regularly,Topper student (85-100),80 to 89
2,Male,1,More than 1 hour,No,No,Primary school (grade 1 - 5),Secondary school (grade 6 - 12),Less than 2 hours,Always,Sometimes,No,More than 2 hours,No,Self studying,Closest date to the exam,Average (40 - 65),60 to 69
3,Male,0,Less than 1 hour,No,Yes,Holds a degree,Secondary school (grade 6 - 12),More than 5 hours,Sometimes,Sometimes,Yes,Less than 2 hours,Yes,"Self studying, Group studying along with friends",I study regularly,Topper student (85-100),80 to 89
4,Male,1,Less than 30 minutes,No,No,Secondary school (grade 6 - 12),Holds a degree,Less than 2 hours,Always,Sometimes,No,None,No,Self studying,Closest date to the exam,Above average (65 - 85),70 to 79
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
137,Male,1,Less than 1 hour,Yes,No,Secondary school (grade 6 - 12),Primary school (grade 1 - 5),Less than 2 hours,Sometimes,Sometimes,Yes,More than 2 hours,Yes,"Self studying, Group studying along with friends",Closest date to the exam,Average (40 - 65),50 to 59
138,Male,1,More than 1 hour,Yes,No,Secondary school (grade 6 - 12),Primary school (grade 1 - 5),Less than 2 hours,Sometimes,Sometimes,No,More than 2 hours,No,Self studying,Closest date to the exam,Average (40 - 65),30 to 39
139,Male,0,More than 1 hour,No,Yes,Secondary school (grade 6 - 12),Secondary school (grade 6 - 12),Less than 1 hour,Sometimes,Sometimes,No,More than 2 hours,Yes,Self studying,Closest date to the exam,Average (40 - 65),40 to 49
140,Female,0,Less than 15 minutes,No,No,Holds a degree,Holds a degree,Less than 1 hour,Sometimes,Sometimes,Yes,More than 2 hours,Yes,Self studying,Closest date to the exam,Below average (less than 40),20 to 29
141,Male,1,Less than 1 hour,No,No,Secondary school (grade 6 - 12),Secondary school (grade 6 - 12),Less than 5 hours,Always,Sometimes,Yes,Less than 2 hours,Yes,"Self studying, Group studying along with frien...",I study regularly,Topper student (85-100),90 to 100

In [86]:
dataMapping={
    "Male":1,
    "Female":0
}

In [87]:
marks_data["Gender"]=marks_data["Gender"].map(dataMapping)
marks_data

,Gender,TravelMethod,TravelTime,PartTimeJob,Relationship,Father's_education,Mother's_education,StudyHours,AttendenceLecs,Concentrate,Friends,SocialMediaTime,extra curricular,HowYouPrepare,StudyPattern,Rate yourself,Marks
0,1,1,Less than 1 hour,No,No,Holds a degree,Holds a degree,Less than 2 hours,Sometimes,Sometimes,Yes,More than 2 hours,Yes,"Self studying, Group studying along with friends",I study regularly,Topper student (85-100),80 to 89
1,1,0,Less than 1 hour,No,Yes,Holds a degree,Secondary school (grade 6 - 12),Less than 5 hours,Sometimes,Sometimes,Yes,Less than 2 hours,Yes,"Self studying, Group studying along with friends",I study regularly,Topper student (85-100),80 to 89
2,1,1,More than 1 hour,No,No,Primary school (grade 1 - 5),Secondary school (grade 6 - 12),Less than 2 hours,Always,Sometimes,No,More than 2 hours,No,Self studying,Closest date to the exam,Average (40 - 65),60 to 69
3,1,0,Less than 1 hour,No,Yes,Holds a degree,Secondary school (grade 6 - 12),More than 5 hours,Sometimes,Sometimes,Yes,Less than 2 hours,Yes,"Self studying, Group studying along with friends",I study regularly,Topper student (85-100),80 to 89
4,1,1,Less than 30 minutes,No,No,Secondary school (grade 6 - 12),Holds a degree,Less than 2 hours,Always,Sometimes,No,None,No,Self studying,Closest date to the exam,Above average (65 - 85),70 to 79
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
137,1,1,Less than 1 hour,Yes,No,Secondary school (grade 6 - 12),Primary school (grade 1 - 5),Less than 2 hours,Sometimes,Sometimes,Yes,More than 2 hours,Yes,"Self studying, Group studying along with friends",Closest date to the exam,Average (40 - 65),50 to 59
138,1,1,More than 1 hour,Yes,No,Secondary school (grade 6 - 12),Primary school (grade 1 - 5),Less than 2 hours,Sometimes,Sometimes,No,More than 2 hours,No,Self studying,Closest date to the exam,Average (40 - 65),30 to 39
139,1,0,More than 1 hour,No,Yes,Secondary school (grade 6 - 12),Secondary school (grade 6 - 12),Less than 1 hour,Sometimes,Sometimes,No,More than 2 hours,Yes,Self studying,Closest date to the exam,Average (40 - 65),40 to 49
140,0,0,Less than 15 minutes,No,No,Holds a degree,Holds a degree,Less than 1 hour,Sometimes,Sometimes,Yes,More than 2 hours,Yes,Self studying,Closest date to the exam,Below average (less than 40),20 to 29
141,1,1,Less than 1 hour,No,No,Secondary school (grade 6 - 12),Secondary school (grade 6 - 12),Less than 5 hours,Always,Sometimes,Yes,Less than 2 hours,Yes,"Self studying, Group studying along with frien...",I study regularly,Topper student (85-100),90 to 100

In [88]:
dataMapping={
    "Yes":1,
    "No":0
}

In [89]:
marks_data["PartTimeJob"]=marks_data["PartTimeJob"].map(dataMapping)
marks_data

,Gender,TravelMethod,TravelTime,PartTimeJob,Relationship,Father's_education,Mother's_education,StudyHours,AttendenceLecs,Concentrate,Friends,SocialMediaTime,extra curricular,HowYouPrepare,StudyPattern,Rate yourself,Marks
0,1,1,Less than 1 hour,0,No,Holds a degree,Holds a degree,Less than 2 hours,Sometimes,Sometimes,Yes,More than 2 hours,Yes,"Self studying, Group studying along with friends",I study regularly,Topper student (85-100),80 to 89
1,1,0,Less than 1 hour,0,Yes,Holds a degree,Secondary school (grade 6 - 12),Less than 5 hours,Sometimes,Sometimes,Yes,Less than 2 hours,Yes,"Self studying, Group studying along with friends",I study regularly,Topper student (85-100),80 to 89
2,1,1,More than 1 hour,0,No,Primary school (grade 1 - 5),Secondary school (grade 6 - 12),Less than 2 hours,Always,Sometimes,No,More than 2 hours,No,Self studying,Closest date to the exam,Average (40 - 65),60 to 69
3,1,0,Less than 1 hour,0,Yes,Holds a degree,Secondary school (grade 6 - 12),More than 5 hours,Sometimes,Sometimes,Yes,Less than 2 hours,Yes,"Self studying, Group studying along with friends",I study regularly,Topper student (85-100),80 to 89
4,1,1,Less than 30 minutes,0,No,Secondary school (grade 6 - 12),Holds a degree,Less than 2 hours,Always,Sometimes,No,None,No,Self studying,Closest date to the exam,Above average (65 - 85),70 to 79
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
137,1,1,Less than 1 hour,1,No,Secondary school (grade 6 - 12),Primary school (grade 1 - 5),Less than 2 hours,Sometimes,Sometimes,Yes,More than 2 hours,Yes,"Self studying, Group studying along with friends",Closest date to the exam,Average (40 - 65),50 to 59
138,1,1,More than 1 hour,1,No,Secondary school (grade 6 - 12),Primary school (grade 1 - 5),Less than 2 hours,Sometimes,Sometimes,No,More than 2 hours,No,Self studying,Closest date to the exam,Average (40 - 65),30 to 39
139,1,0,More than 1 hour,0,Yes,Secondary school (grade 6 - 12),Secondary school (grade 6 - 12),Less than 1 hour,Sometimes,Sometimes,No,More than 2 hours,Yes,Self studying,Closest date to the exam,Average (40 - 65),40 to 49
140,0,0,Less than 15 minutes,0,No,Holds a degree,Holds a degree,Less than 1 hour,Sometimes,Sometimes,Yes,More than 2 hours,Yes,Self studying,Closest date to the exam,Below average (less than 40),20 to 29
141,1,1,Less than 1 hour,0,No,Secondary school (grade 6 - 12),Secondary school (grade 6 - 12),Less than 5 hours,Always,Sometimes,Yes,Less than 2 hours,Yes,"Self studying, Group studying along with frien...",I study regularly,Topper student (85-100),90 to 100

In [90]:
dataMapping={
    "Less than 15 minutes":1,
    "Less than 30 minutes":2,
    "Less than 1 hour":3,
    "More than 1 hour":4
}

In [91]:
marks_data["TravelTime"]=marks_data["TravelTime"].map(dataMapping)
marks_data

,Gender,TravelMethod,TravelTime,PartTimeJob,Relationship,Father's_education,Mother's_education,StudyHours,AttendenceLecs,Concentrate,Friends,SocialMediaTime,extra curricular,HowYouPrepare,StudyPattern,Rate yourself,Marks
0,1,1,3,0,No,Holds a degree,Holds a degree,Less than 2 hours,Sometimes,Sometimes,Yes,More than 2 hours,Yes,"Self studying, Group studying along with friends",I study regularly,Topper student (85-100),80 to 89
1,1,0,3,0,Yes,Holds a degree,Secondary school (grade 6 - 12),Less than 5 hours,Sometimes,Sometimes,Yes,Less than 2 hours,Yes,"Self studying, Group studying along with friends",I study regularly,Topper student (85-100),80 to 89
2,1,1,4,0,No,Primary school (grade 1 - 5),Secondary school (grade 6 - 12),Less than 2 hours,Always,Sometimes,No,More than 2 hours,No,Self studying,Closest date to the exam,Average (40 - 65),60 to 69
3,1,0,3,0,Yes,Holds a degree,Secondary school (grade 6 - 12),More than 5 hours,Sometimes,Sometimes,Yes,Less than 2 hours,Yes,"Self studying, Group studying along with friends",I study regularly,Topper student (85-100),80 to 89
4,1,1,2,0,No,Secondary school (grade 6 - 12),Holds a degree,Less than 2 hours,Always,Sometimes,No,None,No,Self studying,Closest date to the exam,Above average (65 - 85),70 to 79
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
137,1,1,3,1,No,Secondary school (grade 6 - 12),Primary school (grade 1 - 5),Less than 2 hours,Sometimes,Sometimes,Yes,More than 2 hours,Yes,"Self studying, Group studying along with friends",Closest date to the exam,Average (40 - 65),50 to 59
138,1,1,4,1,No,Secondary school (grade 6 - 12),Primary school (grade 1 - 5),Less than 2 hours,Sometimes,Sometimes,No,More than 2 hours,No,Self studying,Closest date to the exam,Average (40 - 65),30 to 39
139,1,0,4,0,Yes,Secondary school (grade 6 - 12),Secondary school (grade 6 - 12),Less than 1 hour,Sometimes,Sometimes,No,More than 2 hours,Yes,Self studying,Closest date to the exam,Average (40 - 65),40 to 49
140,0,0,1,0,No,Holds a degree,Holds a degree,Less than 1 hour,Sometimes,Sometimes,Yes,More than 2 hours,Yes,Self studying,Closest date to the exam,Below average (less than 40),20 to 29
141,1,1,3,0,No,Secondary school (grade 6 - 12),Secondary school (grade 6 - 12),Less than 5 hours,Always,Sometimes,Yes,Less than 2 hours,Yes,"Self studying, Group studying along with frien...",I study regularly,Topper student (85-100),90 to 100

In [92]:
dataMapping={
    "Yes":1,
    "No":0
}

In [93]:
marks_data["Relationship"]=marks_data["Relationship"].map(dataMapping)
marks_data

,Gender,TravelMethod,TravelTime,PartTimeJob,Relationship,Father's_education,Mother's_education,StudyHours,AttendenceLecs,Concentrate,Friends,SocialMediaTime,extra curricular,HowYouPrepare,StudyPattern,Rate yourself,Marks
0,1,1,3,0,0,Holds a degree,Holds a degree,Less than 2 hours,Sometimes,Sometimes,Yes,More than 2 hours,Yes,"Self studying, Group studying along with friends",I study regularly,Topper student (85-100),80 to 89
1,1,0,3,0,1,Holds a degree,Secondary school (grade 6 - 12),Less than 5 hours,Sometimes,Sometimes,Yes,Less than 2 hours,Yes,"Self studying, Group studying along with friends",I study regularly,Topper student (85-100),80 to 89
2,1,1,4,0,0,Primary school (grade 1 - 5),Secondary school (grade 6 - 12),Less than 2 hours,Always,Sometimes,No,More than 2 hours,No,Self studying,Closest date to the exam,Average (40 - 65),60 to 69
3,1,0,3,0,1,Holds a degree,Secondary school (grade 6 - 12),More than 5 hours,Sometimes,Sometimes,Yes,Less than 2 hours,Yes,"Self studying, Group studying along with friends",I study regularly,Topper student (85-100),80 to 89
4,1,1,2,0,0,Secondary school (grade 6 - 12),Holds a degree,Less than 2 hours,Always,Sometimes,No,None,No,Self studying,Closest date to the exam,Above average (65 - 85),70 to 79
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
137,1,1,3,1,0,Secondary school (grade 6 - 12),Primary school (grade 1 - 5),Less than 2 hours,Sometimes,Sometimes,Yes,More than 2 hours,Yes,"Self studying, Group studying along with friends",Closest date to the exam,Average (40 - 65),50 to 59
138,1,1,4,1,0,Secondary school (grade 6 - 12),Primary school (grade 1 - 5),Less than 2 hours,Sometimes,Sometimes,No,More than 2 hours,No,Self studying,Closest date to the exam,Average (40 - 65),30 to 39
139,1,0,4,0,1,Secondary school (grade 6 - 12),Secondary school (grade 6 - 12),Less than 1 hour,Sometimes,Sometimes,No,More than 2 hours,Yes,Self studying,Closest date to the exam,Average (40 - 65),40 to 49
140,0,0,1,0,0,Holds a degree,Holds a degree,Less than 1 hour,Sometimes,Sometimes,Yes,More than 2 hours,Yes,Self studying,Closest date to the exam,Below average (less than 40),20 to 29
141,1,1,3,0,0,Secondary school (grade 6 - 12),Secondary school (grade 6 - 12),Less than 5 hours,Always,Sometimes,Yes,Less than 2 hours,Yes,"Self studying, Group studying along with frien...",I study regularly,Topper student (85-100),90 to 100

In [94]:
dataMapping={
    "Holds a degree":1,
    "Secondary school (grade 6 - 12)":2,
    "Primary school (grade 1 - 5)":3
}

In [95]:
marks_data["Father's_education"]=marks_data["Father's_education"].map(dataMapping)
marks_data["Mother's_education"]=marks_data["Mother's_education"].map(dataMapping)
marks_data

,Gender,TravelMethod,TravelTime,PartTimeJob,Relationship,Father's_education,Mother's_education,StudyHours,AttendenceLecs,Concentrate,Friends,SocialMediaTime,extra curricular,HowYouPrepare,StudyPattern,Rate yourself,Marks
0,1,1,3,0,0,1,1,Less than 2 hours,Sometimes,Sometimes,Yes,More than 2 hours,Yes,"Self studying, Group studying along with friends",I study regularly,Topper student (85-100),80 to 89
1,1,0,3,0,1,1,2,Less than 5 hours,Sometimes,Sometimes,Yes,Less than 2 hours,Yes,"Self studying, Group studying along with friends",I study regularly,Topper student (85-100),80 to 89
2,1,1,4,0,0,3,2,Less than 2 hours,Always,Sometimes,No,More than 2 hours,No,Self studying,Closest date to the exam,Average (40 - 65),60 to 69
3,1,0,3,0,1,1,2,More than 5 hours,Sometimes,Sometimes,Yes,Less than 2 hours,Yes,"Self studying, Group studying along with friends",I study regularly,Topper student (85-100),80 to 89
4,1,1,2,0,0,2,1,Less than 2 hours,Always,Sometimes,No,None,No,Self studying,Closest date to the exam,Above average (65 - 85),70 to 79
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
137,1,1,3,1,0,2,3,Less than 2 hours,Sometimes,Sometimes,Yes,More than 2 hours,Yes,"Self studying, Group studying along with friends",Closest date to the exam,Average (40 - 65),50 to 59
138,1,1,4,1,0,2,3,Less than 2 hours,Sometimes,Sometimes,No,More than 2 hours,No,Self studying,Closest date to the exam,Average (40 - 65),30 to 39
139,1,0,4,0,1,2,2,Less than 1 hour,Sometimes,Sometimes,No,More than 2 hours,Yes,Self studying,Closest date to the exam,Average (40 - 65),40 to 49
140,0,0,1,0,0,1,1,Less than 1 hour,Sometimes,Sometimes,Yes,More than 2 hours,Yes,Self studying,Closest date to the exam,Below average (less than 40),20 to 29
141,1,1,3,0,0,2,2,Less than 5 hours,Always,Sometimes,Yes,Less than 2 hours,Yes,"Self studying, Group studying along with frien...",I study regularly,Topper student (85-100),90 to 100

In [96]:
dataMapping={
    "Less than 1 hour":1,
    "Less than 2 hours":2,
    "Less than 5 hours":3,
    "More than 5 hours":4,
    "None":5
}

In [97]:
marks_data["StudyHours"]=marks_data["StudyHours"].map(dataMapping)
marks_data

,Gender,TravelMethod,TravelTime,PartTimeJob,Relationship,Father's_education,Mother's_education,StudyHours,AttendenceLecs,Concentrate,Friends,SocialMediaTime,extra curricular,HowYouPrepare,StudyPattern,Rate yourself,Marks
0,1,1,3,0,0,1,1,2,Sometimes,Sometimes,Yes,More than 2 hours,Yes,"Self studying, Group studying along with friends",I study regularly,Topper student (85-100),80 to 89
1,1,0,3,0,1,1,2,3,Sometimes,Sometimes,Yes,Less than 2 hours,Yes,"Self studying, Group studying along with friends",I study regularly,Topper student (85-100),80 to 89
2,1,1,4,0,0,3,2,2,Always,Sometimes,No,More than 2 hours,No,Self studying,Closest date to the exam,Average (40 - 65),60 to 69
3,1,0,3,0,1,1,2,4,Sometimes,Sometimes,Yes,Less than 2 hours,Yes,"Self studying, Group studying along with friends",I study regularly,Topper student (85-100),80 to 89
4,1,1,2,0,0,2,1,2,Always,Sometimes,No,None,No,Self studying,Closest date to the exam,Above average (65 - 85),70 to 79
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
137,1,1,3,1,0,2,3,2,Sometimes,Sometimes,Yes,More than 2 hours,Yes,"Self studying, Group studying along with friends",Closest date to the exam,Average (40 - 65),50 to 59
138,1,1,4,1,0,2,3,2,Sometimes,Sometimes,No,More than 2 hours,No,Self studying,Closest date to the exam,Average (40 - 65),30 to 39
139,1,0,4,0,1,2,2,1,Sometimes,Sometimes,No,More than 2 hours,Yes,Self studying,Closest date to the exam,Average (40 - 65),40 to 49
140,0,0,1,0,0,1,1,1,Sometimes,Sometimes,Yes,More than 2 hours,Yes,Self studying,Closest date to the exam,Below average (less than 40),20 to 29
141,1,1,3,0,0,2,2,3,Always,Sometimes,Yes,Less than 2 hours,Yes,"Self studying, Group studying along with frien...",I study regularly,Topper student (85-100),90 to 100

In [98]:
dataMapping={
    "Sometimes":1,
    "Always":2,
    "Never":3
}

In [99]:
marks_data["AttendenceLecs"]=marks_data["AttendenceLecs"].map(dataMapping)
marks_data["Concentrate"]=marks_data["Concentrate"].map(dataMapping)

marks_data

,Gender,TravelMethod,TravelTime,PartTimeJob,Relationship,Father's_education,Mother's_education,StudyHours,AttendenceLecs,Concentrate,Friends,SocialMediaTime,extra curricular,HowYouPrepare,StudyPattern,Rate yourself,Marks
0,1,1,3,0,0,1,1,2,1,1,Yes,More than 2 hours,Yes,"Self studying, Group studying along with friends",I study regularly,Topper student (85-100),80 to 89
1,1,0,3,0,1,1,2,3,1,1,Yes,Less than 2 hours,Yes,"Self studying, Group studying along with friends",I study regularly,Topper student (85-100),80 to 89
2,1,1,4,0,0,3,2,2,2,1,No,More than 2 hours,No,Self studying,Closest date to the exam,Average (40 - 65),60 to 69
3,1,0,3,0,1,1,2,4,1,1,Yes,Less than 2 hours,Yes,"Self studying, Group studying along with friends",I study regularly,Topper student (85-100),80 to 89
4,1,1,2,0,0,2,1,2,2,1,No,None,No,Self studying,Closest date to the exam,Above average (65 - 85),70 to 79
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
137,1,1,3,1,0,2,3,2,1,1,Yes,More than 2 hours,Yes,"Self studying, Group studying along with friends",Closest date to the exam,Average (40 - 65),50 to 59
138,1,1,4,1,0,2,3,2,1,1,No,More than 2 hours,No,Self studying,Closest date to the exam,Average (40 - 65),30 to 39
139,1,0,4,0,1,2,2,1,1,1,No,More than 2 hours,Yes,Self studying,Closest date to the exam,Average (40 - 65),40 to 49
140,0,0,1,0,0,1,1,1,1,1,Yes,More than 2 hours,Yes,Self studying,Closest date to the exam,Below average (less than 40),20 to 29
141,1,1,3,0,0,2,2,3,2,1,Yes,Less than 2 hours,Yes,"Self studying, Group studying along with frien...",I study regularly,Topper student (85-100),90 to 100

In [100]:
dataMapping={
    "Yes":1,
    "No":0
}

In [101]:
marks_data["Friends"]=marks_data["Friends"].map(dataMapping)
marks_data["extra curricular"]=marks_data["extra curricular"].map(dataMapping)

marks_data

,Gender,TravelMethod,TravelTime,PartTimeJob,Relationship,Father's_education,Mother's_education,StudyHours,AttendenceLecs,Concentrate,Friends,SocialMediaTime,extra curricular,HowYouPrepare,StudyPattern,Rate yourself,Marks
0,1,1,3,0,0,1,1,2,1,1,1,More than 2 hours,1,"Self studying, Group studying along with friends",I study regularly,Topper student (85-100),80 to 89
1,1,0,3,0,1,1,2,3,1,1,1,Less than 2 hours,1,"Self studying, Group studying along with friends",I study regularly,Topper student (85-100),80 to 89
2,1,1,4,0,0,3,2,2,2,1,0,More than 2 hours,0,Self studying,Closest date to the exam,Average (40 - 65),60 to 69
3,1,0,3,0,1,1,2,4,1,1,1,Less than 2 hours,1,"Self studying, Group studying along with friends",I study regularly,Topper student (85-100),80 to 89
4,1,1,2,0,0,2,1,2,2,1,0,None,0,Self studying,Closest date to the exam,Above average (65 - 85),70 to 79
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
137,1,1,3,1,0,2,3,2,1,1,1,More than 2 hours,1,"Self studying, Group studying along with friends",Closest date to the exam,Average (40 - 65),50 to 59
138,1,1,4,1,0,2,3,2,1,1,0,More than 2 hours,0,Self studying,Closest date to the exam,Average (40 - 65),30 to 39
139,1,0,4,0,1,2,2,1,1,1,0,More than 2 hours,1,Self studying,Closest date to the exam,Average (40 - 65),40 to 49
140,0,0,1,0,0,1,1,1,1,1,1,More than 2 hours,1,Self studying,Closest date to the exam,Below average (less than 40),20 to 29
141,1,1,3,0,0,2,2,3,2,1,1,Less than 2 hours,1,"Self studying, Group studying along with frien...",I study regularly,Topper student (85-100),90 to 100

In [102]:
dataMapping={
    "Less than 1 hour":1,
    "Less than 2 hours":2,
    "More than 2 hours":3,
    "None":4
}

In [103]:
marks_data["SocialMediaTime"]=marks_data["SocialMediaTime"].map(dataMapping)
marks_data

,Gender,TravelMethod,TravelTime,PartTimeJob,Relationship,Father's_education,Mother's_education,StudyHours,AttendenceLecs,Concentrate,Friends,SocialMediaTime,extra curricular,HowYouPrepare,StudyPattern,Rate yourself,Marks
0,1,1,3,0,0,1,1,2,1,1,1,3,1,"Self studying, Group studying along with friends",I study regularly,Topper student (85-100),80 to 89
1,1,0,3,0,1,1,2,3,1,1,1,2,1,"Self studying, Group studying along with friends",I study regularly,Topper student (85-100),80 to 89
2,1,1,4,0,0,3,2,2,2,1,0,3,0,Self studying,Closest date to the exam,Average (40 - 65),60 to 69
3,1,0,3,0,1,1,2,4,1,1,1,2,1,"Self studying, Group studying along with friends",I study regularly,Topper student (85-100),80 to 89
4,1,1,2,0,0,2,1,2,2,1,0,4,0,Self studying,Closest date to the exam,Above average (65 - 85),70 to 79
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
137,1,1,3,1,0,2,3,2,1,1,1,3,1,"Self studying, Group studying along with friends",Closest date to the exam,Average (40 - 65),50 to 59
138,1,1,4,1,0,2,3,2,1,1,0,3,0,Self studying,Closest date to the exam,Average (40 - 65),30 to 39
139,1,0,4,0,1,2,2,1,1,1,0,3,1,Self studying,Closest date to the exam,Average (40 - 65),40 to 49
140,0,0,1,0,0,1,1,1,1,1,1,3,1,Self studying,Closest date to the exam,Below average (less than 40),20 to 29
141,1,1,3,0,0,2,2,3,2,1,1,2,1,"Self studying, Group studying along with frien...",I study regularly,Topper student (85-100),90 to 100

In [104]:
dataMapping={
    "Self studying":1,
    "Group studying along with friends":2,
    "Help of a tutor":3,
    "Self studying, Group studying along with friends":4,
    "Self studying, Help of a tutor":5,
    "Group studying along with friends, Help of a tutor":6,
    "Self studying, Group studying along with friends, Help of a tutor":7
}

In [105]:
marks_data["HowYouPrepare"]=marks_data["HowYouPrepare"].map(dataMapping)
marks_data

,Gender,TravelMethod,TravelTime,PartTimeJob,Relationship,Father's_education,Mother's_education,StudyHours,AttendenceLecs,Concentrate,Friends,SocialMediaTime,extra curricular,HowYouPrepare,StudyPattern,Rate yourself,Marks
0,1,1,3,0,0,1,1,2,1,1,1,3,1,4,I study regularly,Topper student (85-100),80 to 89
1,1,0,3,0,1,1,2,3,1,1,1,2,1,4,I study regularly,Topper student (85-100),80 to 89
2,1,1,4,0,0,3,2,2,2,1,0,3,0,1,Closest date to the exam,Average (40 - 65),60 to 69
3,1,0,3,0,1,1,2,4,1,1,1,2,1,4,I study regularly,Topper student (85-100),80 to 89
4,1,1,2,0,0,2,1,2,2,1,0,4,0,1,Closest date to the exam,Above average (65 - 85),70 to 79
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
137,1,1,3,1,0,2,3,2,1,1,1,3,1,4,Closest date to the exam,Average (40 - 65),50 to 59
138,1,1,4,1,0,2,3,2,1,1,0,3,0,1,Closest date to the exam,Average (40 - 65),30 to 39
139,1,0,4,0,1,2,2,1,1,1,0,3,1,1,Closest date to the exam,Average (40 - 65),40 to 49
140,0,0,1,0,0,1,1,1,1,1,1,3,1,1,Closest date to the exam,Below average (less than 40),20 to 29
141,1,1,3,0,0,2,2,3,2,1,1,2,1,7,I study regularly,Topper student (85-100),90 to 100

In [106]:
dataMapping={
    "I study regularly":1,
    "Closest date to the exam":2,
}

In [107]:
marks_data["StudyPattern"]=marks_data["StudyPattern"].map(dataMapping)
marks_data

,Gender,TravelMethod,TravelTime,PartTimeJob,Relationship,Father's_education,Mother's_education,StudyHours,AttendenceLecs,Concentrate,Friends,SocialMediaTime,extra curricular,HowYouPrepare,StudyPattern,Rate yourself,Marks
0,1,1,3,0,0,1,1,2,1,1,1,3,1,4,1,Topper student (85-100),80 to 89
1,1,0,3,0,1,1,2,3,1,1,1,2,1,4,1,Topper student (85-100),80 to 89
2,1,1,4,0,0,3,2,2,2,1,0,3,0,1,2,Average (40 - 65),60 to 69
3,1,0,3,0,1,1,2,4,1,1,1,2,1,4,1,Topper student (85-100),80 to 89
4,1,1,2,0,0,2,1,2,2,1,0,4,0,1,2,Above average (65 - 85),70 to 79
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
137,1,1,3,1,0,2,3,2,1,1,1,3,1,4,2,Average (40 - 65),50 to 59
138,1,1,4,1,0,2,3,2,1,1,0,3,0,1,2,Average (40 - 65),30 to 39
139,1,0,4,0,1,2,2,1,1,1,0,3,1,1,2,Average (40 - 65),40 to 49
140,0,0,1,0,0,1,1,1,1,1,1,3,1,1,2,Below average (less than 40),20 to 29
141,1,1,3,0,0,2,2,3,2,1,1,2,1,7,1,Topper student (85-100),90 to 100

In [108]:
dataMapping={
    "Topper student (85-100)":1,
    "Above average (65 - 85)":2,
    "Average (40 - 65)":3,
    "Below average (less than 40)":4
}

In [109]:
marks_data["Rate yourself"]=marks_data["Rate yourself"].map(dataMapping)
marks_data

,Gender,TravelMethod,TravelTime,PartTimeJob,Relationship,Father's_education,Mother's_education,StudyHours,AttendenceLecs,Concentrate,Friends,SocialMediaTime,extra curricular,HowYouPrepare,StudyPattern,Rate yourself,Marks
0,1,1,3,0,0,1,1,2,1,1,1,3,1,4,1,1,80 to 89
1,1,0,3,0,1,1,2,3,1,1,1,2,1,4,1,1,80 to 89
2,1,1,4,0,0,3,2,2,2,1,0,3,0,1,2,3,60 to 69
3,1,0,3,0,1,1,2,4,1,1,1,2,1,4,1,1,80 to 89
4,1,1,2,0,0,2,1,2,2,1,0,4,0,1,2,2,70 to 79
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
137,1,1,3,1,0,2,3,2,1,1,1,3,1,4,2,3,50 to 59
138,1,1,4,1,0,2,3,2,1,1,0,3,0,1,2,3,30 to 39
139,1,0,4,0,1,2,2,1,1,1,0,3,1,1,2,3,40 to 49
140,0,0,1,0,0,1,1,1,1,1,1,3,1,1,2,4,20 to 29
141,1,1,3,0,0,2,2,3,2,1,1,2,1,7,1,1,90 to 100

In [205]:
x= marks_data.drop(columns='Marks')
y= marks_data['Marks']

In [206]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3)

In [207]:
from sklearn.preprocessing import StandardScaler

In [208]:
scaler = StandardScaler()

In [209]:
x_train_scaled = scaler.fit_transform(x_train)

In [210]:
x_test_scaled = scaler.transform(x_test)

In [211]:
x_test_scaled

array([[-1.09544512,  0.95070824, -1.65471336, -0.73950997, -0.6751906 ,
        -0.76013979, -1.15039626,  0.46911664,  0.85993942, -0.54590804,
         0.51887452, -0.8758299 , -1.18938394,  0.72219993,  0.62798583,
        -0.31418936],
       [ 0.91287093,  0.95070824, -1.65471336, -0.73950997,  1.48106326,
         0.98994949, -1.15039626,  1.39796759, -1.07492427, -0.54590804,
         0.51887452,  0.59378298,  0.8407714 , -0.92774914,  0.62798583,
        -0.31418936],
       [-1.09544512, -1.05184741, -0.66786624, -0.73950997,  1.48106326,
        -0.76013979,  0.52444536,  0.46911664,  0.85993942, -0.54590804,
         0.51887452,  0.59378298, -1.18938394, -0.92774914,  0.62798583,
        -0.31418936],
       [-1.09544512, -1.05184741, -0.66786624, -0.73950997, -0.6751906 ,
        -0.76013979, -1.15039626, -0.45973431,  0.85993942, -0.54590804,
         0.51887452,  0.59378298,  0.8407714 ,  0.72219993,  0.62798583,
         0.88214705],
       [-1.09544512,  0.95070824, -0.66786624, -0.73950997, -0.6751906 ,
        -0.76013979,  0.52444536,  0.46911664,  0.85993942,  1.31770907,
         0.51887452, -2.34544277, -1.18938394,  0.72219993,  0.62798583,
        -0.31418936],
       [ 0.91287093,  0.95070824, -1.65471336, -0.73950997, -0.6751906 ,
        -0.76013979, -1.15039626,  0.46911664, -1.07492427, -0.54590804,
        -1.92724822, -0.8758299 ,  0.8407714 , -0.92774914,  0.62798583,
        -1.51052576],
       [ 0.91287093,  0.95070824,  1.30582801, -0.73950997, -0.6751906 ,
         0.98994949,  0.52444536,  1.39796759,  0.85993942,  1.31770907,
         0.51887452, -2.34544277, -1.18938394, -0.92774914, -1.59239263,
        -1.51052576],
       [-1.09544512,  0.95070824, -0.66786624, -0.73950997, -0.6751906 ,
        -0.76013979, -1.15039626,  1.39796759,  0.85993942,  1.31770907,
         0.51887452, -0.8758299 , -1.18938394, -0.92774914,  0.62798583,
        -0.31418936],
       [-1.09544512,  0.95070824,  0.31898089,  1.35224681,  1.48106326,
        -0.76013979, -1.15039626,  0.46911664,  0.85993942,  1.31770907,
         0.51887452, -2.34544277, -1.18938394,  0.17221691,  0.62798583,
         0.88214705],
       [-1.09544512, -1.05184741, -1.65471336, -0.73950997, -0.6751906 ,
        -0.76013979, -1.15039626, -0.45973431,  0.85993942, -0.54590804,
         0.51887452,  0.59378298,  0.8407714 , -0.92774914,  0.62798583,
         0.88214705],
       [ 0.91287093, -1.05184741, -1.65471336, -0.73950997, -0.6751906 ,
         0.98994949,  0.52444536,  1.39796759,  0.85993942, -0.54590804,
         0.51887452,  0.59378298, -1.18938394,  0.72219993,  0.62798583,
        -0.31418936],
       [-1.09544512,  0.95070824, -0.66786624, -0.73950997, -0.6751906 ,
        -0.76013979,  0.52444536,  0.46911664,  0.85993942,  1.31770907,
         0.51887452, -2.34544277, -1.18938394, -0.92774914, -1.59239263,
        -0.31418936],
       [ 0.91287093,  0.95070824,  1.30582801, -0.73950997, -0.6751906 ,
         0.98994949,  0.52444536,  0.46911664, -1.07492427, -0.54590804,
         0.51887452, -0.8758299 , -1.18938394, -0.92774914,  0.62798583,
        -0.31418936],
       [ 0.91287093,  0.95070824,  1.30582801, -0.73950997, -0.6751906 ,
         0.98994949,  0.52444536, -1.38858526, -1.07492427, -0.54590804,
         0.51887452,  0.59378298, -1.18938394,  1.82216598,  0.62798583,
        -0.31418936],
       [-1.09544512, -1.05184741, -1.65471336, -0.73950997, -0.6751906 ,
         0.98994949,  0.52444536,  1.39796759,  0.85993942, -0.54590804,
         0.51887452,  0.59378298,  0.8407714 ,  0.72219993,  0.62798583,
        -1.51052576],
       [ 0.91287093,  0.95070824,  1.30582801, -0.73950997,  1.48106326,
         0.98994949, -1.15039626, -1.38858526, -1.07492427,  3.18132618,
        -1.92724822,  2.06339586,  0.8407714 , -0.92774914,  0.62798583,
         2.07848345],
       [-1.09544512, -1.05184741,  1.30582801, -0.73950997, -0.6751906 ,
        -0.76013979, -1.15039626, -0.45973431,  0.85993942,  1.31770907,
         0.51887452,  0.59378298, -1.18938394,  0.72219993, -1.59239263,
         0.88214705],
       [-1.09544512,  0.95070824,  1.30582801, -0.73950997, -0.6751906 ,
         0.98994949, -1.15039626, -1.38858526,  2.7948031 , -0.54590804,
        -1.92724822,  0.59378298, -1.18938394, -0.92774914,  0.62798583,
         2.07848345],
       [ 0.91287093,  0.95070824,  0.31898089, -0.73950997, -0.6751906 ,
         0.98994949,  0.52444536, -0.45973431,  0.85993942, -0.54590804,
         0.51887452,  0.59378298,  0.8407714 ,  2.37214901,  0.62798583,
        -0.31418936],
       [ 0.91287093,  0.95070824,  1.30582801, -0.73950997, -0.6751906 ,
        -0.76013979,  0.52444536,  2.32681854, -1.07492427, -0.54590804,
         0.51887452,  0.59378298,  0.8407714 ,  2.37214901,  0.62798583,
        -0.31418936],
       [-1.09544512,  0.95070824,  1.30582801,  1.35224681,  1.48106326,
         2.74003878,  2.19928697,  1.39796759,  0.85993942,  1.31770907,
        -1.92724822, -2.34544277, -1.18938394, -0.92774914, -1.59239263,
        -0.31418936],
       [ 0.91287093,  0.95070824,  0.31898089, -0.73950997,  1.48106326,
         0.98994949,  2.19928697, -1.38858526, -1.07492427, -0.54590804,
        -1.92724822, -2.34544277, -1.18938394, -0.92774914,  0.62798583,
         0.88214705],
       [ 0.91287093,  0.95070824,  1.30582801, -0.73950997, -0.6751906 ,
        -0.76013979, -1.15039626,  0.46911664, -1.07492427, -0.54590804,
         0.51887452,  0.59378298, -1.18938394, -0.92774914, -1.59239263,
        -0.31418936],
       [-1.09544512,  0.95070824,  1.30582801, -0.73950997,  1.48106326,
         0.98994949,  0.52444536, -1.38858526, -1.07492427, -0.54590804,
        -1.92724822,  0.59378298,  0.8407714 ,  0.72219993,  0.62798583,
         2.07848345],
       [-1.09544512,  0.95070824, -0.66786624, -0.73950997,  1.48106326,
        -0.76013979,  0.52444536,  2.32681854,  0.85993942, -0.54590804,
         0.51887452,  0.59378298, -1.18938394, -0.92774914,  0.62798583,
        -0.31418936],
       [-1.09544512,  0.95070824,  1.30582801, -0.73950997, -0.6751906 ,
        -0.76013979,  0.52444536,  0.46911664,  0.85993942, -0.54590804,
         0.51887452, -0.8758299 ,  0.8407714 , -0.92774914,  0.62798583,
        -0.31418936],
       [-1.09544512, -1.05184741,  0.31898089, -0.73950997,  1.48106326,
         0.98994949, -1.15039626, -0.45973431,  0.85993942, -0.54590804,
         0.51887452,  0.59378298, -1.18938394, -0.92774914,  0.62798583,
        -0.31418936],
       [-1.09544512, -1.05184741, -0.66786624,  1.35224681, -0.6751906 ,
        -0.76013979,  0.52444536,  0.46911664,  0.85993942,  1.31770907,
         0.51887452,  0.59378298,  0.8407714 ,  0.72219993, -1.59239263,
        -0.31418936],
       [-1.09544512, -1.05184741, -1.65471336, -0.73950997, -0.6751906 ,
        -0.76013979, -1.15039626, -0.45973431,  0.85993942, -0.54590804,
        -1.92724822,  0.59378298, -1.18938394, -0.92774914,  0.62798583,
        -0.31418936],
       [-1.09544512, -1.05184741, -0.66786624, -0.73950997,  1.48106326,
        -0.76013979, -1.15039626,  1.39796759,  0.85993942, -0.54590804,
        -1.92724822, -2.34544277, -1.18938394, -0.92774914, -1.59239263,
        -0.31418936],
       [ 0.91287093, -1.05184741,  0.31898089,  1.35224681, -0.6751906 ,
         0.98994949, -1.15039626, -1.38858526, -1.07492427, -0.54590804,
        -1.92724822, -0.8758299 ,  0.8407714 , -0.92774914,  0.62798583,
        -0.31418936],
       [ 0.91287093, -1.05184741, -1.65471336, -0.73950997, -0.6751906 ,
         0.98994949, -1.15039626,  0.46911664, -1.07492427, -0.54590804,
        -1.92724822,  0.59378298,  0.8407714 , -0.92774914,  0.62798583,
        -0.31418936],
       [-1.09544512,  0.95070824, -1.65471336, -0.73950997, -0.6751906 ,
        -0.76013979, -1.15039626,  0.46911664,  0.85993942, -0.54590804,
         0.51887452,  0.59378298,  0.8407714 , -0.92774914,  0.62798583,
        -0.31418936],
       [ 0.91287093,  0.95070824,  1.30582801, -0.73950997, -0.6751906 ,
         2.74003878,  0.52444536, -0.45973431,  0.85993942, -0.54590804,
        -1.92724822,  0.59378298, -1.18938394, -0.92774914,  0.62798583,
         0.88214705],
       [ 0.91287093, -1.05184741, -0.66786624, -0.73950997, -0.6751906 ,
         0.98994949, -1.15039626, -0.45973431, -1.07492427, -0.54590804,
         0.51887452,  0.59378298, -1.18938394,  0.72219993,  0.62798583,
        -0.31418936],
       [ 0.91287093, -1.05184741,  0.31898089, -0.73950997,  1.48106326,
        -0.76013979,  0.52444536,  1.39796759,  0.85993942,  3.18132618,
         0.51887452, -0.8758299 ,  0.8407714 ,  0.72219993, -1.59239263,
        -0.31418936],
       [ 0.91287093,  0.95070824,  1.30582801, -0.73950997,  1.48106326,
        -0.76013979, -1.15039626, -0.45973431,  0.85993942, -0.54590804,
         0.51887452, -0.8758299 ,  0.8407714 ,  2.37214901,  0.62798583,
         0.88214705],
       [-1.09544512, -1.05184741, -1.65471336,  1.35224681, -0.6751906 ,
         0.98994949,  0.52444536, -0.45973431, -1.07492427, -0.54590804,
         0.51887452, -2.34544277, -1.18938394, -0.92774914,  0.62798583,
         0.88214705],
       [ 0.91287093, -1.05184741,  1.30582801, -0.73950997,  1.48106326,
         0.98994949,  0.52444536, -1.38858526, -1.07492427, -0.54590804,
        -1.92724822,  0.59378298,  0.8407714 , -0.92774914,  0.62798583,
         0.88214705],
       [-1.09544512, -1.05184741, -0.66786624,  1.35224681, -0.6751906 ,
         0.98994949,  0.52444536, -0.45973431,  0.85993942,  1.31770907,
         0.51887452,  0.59378298, -1.18938394,  0.72219993,  0.62798583,
        -1.51052576],
       [ 0.91287093,  0.95070824, -1.65471336, -0.73950997, -0.6751906 ,
         0.98994949,  2.19928697,  0.46911664, -1.07492427, -0.54590804,
        -1.92724822,  0.59378298,  0.8407714 ,  1.27218296,  0.62798583,
        -0.31418936],
       [ 0.91287093, -1.05184741, -1.65471336,  1.35224681,  1.48106326,
         0.98994949,  0.52444536, -0.45973431, -1.07492427, -0.54590804,
         0.51887452, -0.8758299 ,  0.8407714 ,  2.37214901, -1.59239263,
        -1.51052576],
       [-1.09544512,  0.95070824,  0.31898089, -0.73950997, -0.6751906 ,
         0.98994949,  0.52444536,  0.46911664,  0.85993942, -0.54590804,
         0.51887452,  0.59378298, -1.18938394,  2.37214901,  0.62798583,
        -0.31418936]])

In [212]:
from sklearn.linear_model import LogisticRegression

In [213]:
log_reg = LogisticRegression(random_state =0).fit(x_train_scaled, y_train)

In [214]:
log_reg.predict(x_train_scaled)

array(['30 to 39', '70 to 79', '80 to 89', '80 to 89', '20 to 29',
       '70 to 79', '70 to 79', '70 to 79', '60 to 69', '70 to 79',
       '60 to 69', '70 to 79', '70 to 79', '70 to 79', '80 to 89',
       '70 to 79', '40 to 49', '70 to 79', '80 to 89', '90 to 100',
       '70 to 79', '60 to 69', '70 to 79', '70 to 79', '90 to 100',
       '80 to 89', '50 to 59', '30 to 39', '70 to 79', '70 to 79',
       '0 to 20', '80 to 89', '50 to 59', '40 to 49', '90 to 100',
       '40 to 49', '30 to 39', '40 to 49', '70 to 79', '80 to 89',
       '70 to 79', '0 to 20', '60 to 69', '30 to 39', '80 to 89',
       '70 to 79', '70 to 79', '80-100', '80 to 89', '70 to 79',
       '70 to 79', '70 to 79', '80 to 89', '30 to 39', '70 to 79',
       '80 to 89', '50 to 59', '80 to 89', '80-100', '60 to 69',
       '70 to 79', '70 to 79', '80 to 89', '70 to 79', '30 to 39',
       '70 to 79', '70 to 79', '80 to 89', '60 to 69', '70 to 79',
       '20 to 29', '70 to 79', '0 to 20', '70 to 79', '30 to 39',
       '80 to 89', '70 to 79', '70 to 79', '40 to 49', '70 to 79',
       '20 to 29', '60 to 69', '50 to 59', '70 to 79', '80 to 89',
       '40 to 49', '70 to 79', '80 to 89', '80 to 89', '60 to 69',
       '80 to 89', '60 to 69', '80 to 89', '70 to 79', '80 to 89',
       '60 to 69', '70 to 79', '80 to 89', '90 to 100'], dtype=object)

In [215]:
log_reg.score(x_train_scaled, y_train)

0.7474747474747475

In [216]:
log_reg.score(x_test_scaled, y_test)

0.27906976744186046